CREATE TABLE RADIO_STATION
(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(16) NOT NULL,
    URL VARCHAR(128) NOT NULL,
    CHANNEL INT NOT NULL
);

CREATE TABLE CONFIGURATION
(
    CONFIG_KEY VARCHAR(16) NOT NULL UNIQUE,
    CONFIG_VALUE VARCHAR(16) NOT NULL
);